TMDT-Lab05-1212100/MVCWebAPIClient1212100/Controllers/DefaultController.cs
using MVCWebAPIClient1212100.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace MVCWebAPIClient1212100.Controllers
{
    public class DefaultController : Controller
    {
        //
        // GET: /Default/
        public ActionResult Index()
        {
            GetAllUser list = new GetAllUser();
            list.listUsers = new List<NguoiDung>();
            return View(list);
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            using (var c = new HttpClient())
            {
                c.BaseAddress = new Uri("http://localhost:22337/");
                c.DefaultRequestHeaders.Accept.Clear();
                c.DefaultRequestHeaders.Accept.Add(
               new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage response = c.GetAsync("api/2.0/users").Result;
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    GetAllUser list = new GetAllUser();
                    list.listUsers = new List<NguoiDung>();
                    list.listUsers = response.Content.ReadAsAsync<List<NguoiDung>>().Result;
                    return View(list);
                }
            }
            return View();
        }

        public ActionResult GetUserByUsername()
        {
            NguoiDung nd = new NguoiDung();
            return View(nd);
        }

        [HttpPost]
        public ActionResult GetUserByUsername(FormCollection form)
        {
            string strUsername = form["txtUsername"].ToString();
            NguoiDung nd = new NguoiDung();

            using (var c = new HttpClient())
            {
                c.BaseAddress = new Uri("http://localhost:22337/");
                c.DefaultRequestHeaders.Accept.Clear();
                c.DefaultRequestHeaders.Accept.Add(
               new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage response = c.GetAsync("api/2.0/users/" + strUsername).Result;
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    
                    nd = response.Content.ReadAsAsync<NguoiDung>().Result;
                    return View(nd);
                }
            }
            return View(nd);
        }



        public ActionResult UpdateUser()
        {
            ViewBag.MS = "";
            return View();
        }

        [HttpPost]
        public ActionResult UpdateUser(FormCollection form)
        {
            string strUsername = form["txtUsernamePut"].ToString();
            string strNewPassword = form["txtNewPasswordPut"].ToString();

            ViewBag.MS = "";
            using (var c = new HttpClient())
            {
                c.BaseAddress = new Uri("http://localhost:22337/");
                c.DefaultRequestHeaders.Accept.Clear();
                c.DefaultRequestHeaders.Accept.Add(
               new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage response = c.PutAsJsonAsync("api/2.0/users/" + strUsername,strNewPassword).Result;
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    ViewBag.MS = "Success Update";
                    
                    return View();
                }
            }
            return View();
        }



        public ActionResult DeleteUser()
        {
            ViewBag.MS = "";
            return View();
        }

        [HttpPost]
        public ActionResult DeleteUser(FormCollection form)
        {
            string strUsername = form["txtUsernameDelete"].ToString();
            

            ViewBag.MS = "";
            using (var c = new HttpClient())
            {
                c.BaseAddress = new Uri("http://localhost:22337/");
                c.DefaultRequestHeaders.Accept.Clear();
                c.DefaultRequestHeaders.Accept.Add(
               new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage response = c.DeleteAsync("api/2.0/users/" + strUsername).Result;
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    ViewBag.MS = "Success Delete";

                    return View();
                }
            }
            return View();
        }



        public ActionResult AddUser()
        {
            ViewBag.MS = "";
            return View();
        }

        [HttpPost]
        public ActionResult AddUser(FormCollection form)
        {
            string strUsername = form["txtNewUsername"].ToString();
            string strPassword = form["txtNewPassword"].ToString();


            ViewBag.MS = "";
            using (var c = new HttpClient())
            {
                c.BaseAddress = new Uri("http://localhost:22337/");
                c.DefaultRequestHeaders.Accept.Clear();
                c.DefaultRequestHeaders.Accept.Add(
               new MediaTypeWithQualityHeaderValue("application/json"));

                var model = new {username = strUsername, password = strPassword };

                HttpResponseMessage response = c.PostAsJsonAsync("api/2.0/users", model).Result;
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    ViewBag.MS = "Success Add";

                    return View();
                }
            }
            return View();
        }



	}
}

TMDT-Lab05-1212100/MVCWebAPIClient1212100/Controllers/ProductController.cs
using MVCWebAPIClient1212100.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace MVCWebAPIClient1212100.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        public ActionResult GetProductByCategory()
        {
            GetAllProduct list = new GetAllProduct();
            list.listofProduct = new List<SanPham>();
            return View(list);
        }

        [HttpPost]
        public ActionResult GetProductByCategory(FormCollection form)
        {
            GetAllProduct list = new GetAllProduct();
            list.listofProduct = new List<SanPham>();

            string strCategory = form["txtCategory"].ToString();

            using (var c = new HttpClient())
            {
                c.BaseAddress = new Uri("http://localhost:22337/");
                c.DefaultRequestHeaders.Accept.Clear();
                c.DefaultRequestHeaders.Accept.Add(
               new MediaTypeWithQualityHeaderValue("application/json"));


                HttpResponseMessage response = c.GetAsync("api/2.0/products/" + strCategory).Result;
                if (response.StatusCode == HttpStatusCode.OK)
                {
                   
                    list.listofProduct = response.Content.ReadAsAsync<List<SanPham>>().Result;
                    return View(list);
                }
            }
            return View(list);
        }









        public ActionResult GetProductByCategoryAndUsername()
        {
            GetAllProduct list = new GetAllProduct();
            list.listofProduct = new List<SanPham>();
            return View(list);
        }

        [HttpPost]
        public ActionResult GetProductByCategoryAndUsername(FormCollection form)
        {
            GetAllProduct list = new GetAllProduct();
            list.listofProduct = new List<SanPham>();

            string strCategorySearch = form["txtCategorySearch"].ToString();
            string strUsernameSearch = form["txtUsernameSearch"].ToString();
            

            using (var c = new HttpClient())
            {
                c.BaseAddress = new Uri("http://localhost:22337/");
                c.DefaultRequestHeaders.Accept.Clear();
                c.DefaultRequestHeaders.Accept.Add(
               new MediaTypeWithQualityHeaderValue("application/json"));

               
                HttpResponseMessage response = c.GetAsync("api/2.0/products/" + strCategorySearch + "/" + strUsernameSearch).Result;
                if (response.StatusCode == HttpStatusCode.OK)
                {

                    list.listofProduct = response.Content.ReadAsAsync<List<SanPham>>().Result;
                    return View(list);
                }
            }
            return View(list);
        }
	}
}

TMDT-Lab05-1212100/MVCWebAPIClient1212100/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                   
                </ul>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TMDT-Lab05-1212100/MVCWebAPIClient1212100/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <ul id="menu">
        <li><a href="@Url.Action("Index", "Default")">Get All User</a></li>
        <li><a href="@Url.Action("GetUserByUsername", "Default")">Get User By Username</a></li>
        <li><a href="@Url.Action("GetProductByCategory", "Product")">Get Product By Category</a></li>
        <li><a href="@Url.Action("GetProductByCategoryAndUsername", "Product")">Get Product By Category and Username</a></li>
        <li><a href="@Url.Action("AddUser", "Default")">Add User</a></li>
        <li><a href="@Url.Action("DeleteUser", "Default")">Delete User By Usernamee</a></li>
        <li><a href="@Url.Action("UpdateUser", "Default")">Update User By Username</a></li>
        
    </ul>


    <div>
        @RenderBody()
    </div>
</body>
</html>